---
substitutions:
  MODBUS_SEND_DELAY: 100ms
  MODBUS_TICK_INTERVAL: 10000ms
  MODBUS_SKIP_TICKS_IMMUTABLE: 359  # Collect static data every 360 ticks (1 hour)
  MODBUS_SKIP_TICKS_SLOW: 5  # Collect slow-varying data every 6 ticks (1 min)
  MODBUS_NO_VARIATION_HEARTBEAT: 60s
  SCALING_FACTOR_WHRtg: -2
  SCALING_FACTOR_W: 0
  SCALING_FACTOR_SoC: -1
  SCALING_FACTOR_SoH: 0
  SCALING_FACTOR_V: -1
  SCALING_FACTOR_A: -1
  SCALING_FACTOR_Energy: -2
  SCALING_FACTOR_Temp: -1
globals:
  - id: mult_WHRtg
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_WHRtg})"
    restore_value: false
  - id: mult_W
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_W})"
    restore_value: false
  - id: mult_SoC
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_SoC})"
    restore_value: false
  - id: div_SoC
    type: float
    initial_value: "1.0f / powf(10.0f, ${SCALING_FACTOR_SoC})"
    restore_value: false
  - id: mult_SoH
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_SoH})"
    restore_value: false
  - id: mult_V
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_V})"
    restore_value: false
  - id: mult_A
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_A})"
    restore_value: false
  - id: mult_Energy
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_Energy})"
    restore_value: false
  - id: mult_Temp
    type: float
    initial_value: "powf(10.0f, ${SCALING_FACTOR_Temp})"
    restore_value: false
