---
modbus_controller:
  - id: elt12k_modbus
    address: 1            # Slave target address
    modbus_id: modbus_bus
    setup_priority: -10
    update_interval: ${MODBUS_TICK_INTERVAL}  # Tick interval for collection
    command_throttle: 300ms
    # Triggers that track live RS485 communication stability
    on_online:
      then:
        - binary_sensor.template.publish:
            id: modbus_cx_status
            state: ON
    on_offline:
      then:
        - binary_sensor.template.publish:
            id: modbus_cx_status
            state: OFF
    on_command_sent:
      then:
        - lambda: |-
            id(modbus_counter_raw)++;
            id(modbus_command_count).publish_state(id(modbus_counter_raw));

binary_sensor:
  - id: modbus_cx_status
    platform: template
    name: modbus_connection_status
    icon: mdi:server-network
    device_class: connectivity
    web_server:
      sorting_group_id: alerts

globals:
  - id: modbus_counter_raw
    type: uint32_t
    restore_value: false  # Do not persist across reboots
    initial_value: '0'

sensor:
  - id: modbus_command_count
    platform: template
    name: modbus_command_count
    icon: mdi:server-network
    accuracy_decimals: 0
    state_class: total_increasing
    web_server:
      sorting_group_id: sys_health
