---
text_sensor:
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    name: "system_info_manufacturer"
    icon: mdi:factory
    address: 40004
    register_type: holding
    register_count: 8
    response_size: 16
    raw_encode: ANSI
    skip_updates: ${MODBUS_SKIP_TICKS_IMMUTABLE}
    web_server:
      sorting_group_id: sys_info
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    name: "system_info_model"
    icon: mdi:cube-outline
    address: 40020
    register_type: holding
    register_count: 8
    response_size: 16
    raw_encode: ANSI
    skip_updates: ${MODBUS_SKIP_TICKS_IMMUTABLE}
    web_server:
      sorting_group_id: sys_info
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    name: "system_info_sw_version"
    icon: mdi:code-tags
    address: 40044
    register_type: holding
    register_count: 4
    response_size: 8
    raw_encode: ANSI
    skip_updates: ${MODBUS_SKIP_TICKS_IMMUTABLE}
    web_server:
      sorting_group_id: sys_info
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    name: "system_info_serial_number"
    icon: mdi:numeric
    address: 40052
    register_type: holding
    register_count: 8
    response_size: 16
    raw_encode: ANSI
    skip_updates: ${MODBUS_SKIP_TICKS_IMMUTABLE}
    web_server:
      sorting_group_id: sys_info
sensor:
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    address: 40089
    register_type: holding
    value_type: U_WORD
    name: "system_heartbeat"
    icon: mdi:heart-pulse
    filters:
      - or:
          - delta: 1.0
          - heartbeat: ${MODBUS_NO_VARIATION_HEARTBEAT}
    web_server:
      sorting_group_id: sys_health
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    address: 40156
    register_type: holding
    value_type: S_WORD
    name: "battery_temp"
    icon: mdi:thermometer
    unit_of_measurement: "C"
    device_class: temperature
    accuracy_decimals: 1
    skip_updates: ${MODBUS_SKIP_TICKS_IMMUTABLE}
    lambda: "return x * id(mult_Temp);"
    web_server:
      sorting_group_id: sys_health
  - platform: modbus_controller
    modbus_controller_id: elt12k_modbus
    address: 40157
    register_type: holding
    value_type: S_WORD
    name: "system_temp"
    icon: mdi:thermometer
    unit_of_measurement: "C"
    device_class: temperature
    accuracy_decimals: 1
    skip_updates: ${MODBUS_SKIP_TICKS_IMMUTABLE}
    lambda: "return x * id(mult_Temp);"
    web_server:
      sorting_group_id: sys_health
