---
modbus_controller:
  - id: elt12k_modbus
    address: 1
    modbus_id: modbus_bus
    setup_priority: -10
    update_interval: ${MODBUS_TICK_INTERVAL}
    offline_skip_updates: 5
    on_online:
      then:
        - binary_sensor.template.publish:
            id: modbus_cx_status
            state: ON
        - lambda: ESP_LOGI("modbus", "Modbus connection active");
    on_offline:
      then:
        - binary_sensor.template.publish:
            id: modbus_cx_status
            state: OFF
        - lambda: |-
            ESP_LOGW("modbus", "Lost Modbus connection to ELT-12K, retrying after 5 missed requests");
            id(modbus_bus).setup();
    on_command_sent:
      then:
        - lambda: id(modbus_counter_raw)++;

binary_sensor:
  - id: modbus_cx_status
    platform: template
    name: modbus_connection_status
    icon: mdi:server-network
    device_class: connectivity
    web_server:
      sorting_group_id: alerts

globals:
  - id: modbus_counter_raw
    type: uint32_t
    restore_value: false  # Do not persist across reboots
    initial_value: '0'

sensor:
  - id: modbus_command_count
    platform: template
    name: modbus_command_count
    icon: mdi:server-network
    accuracy_decimals: 0
    state_class: total_increasing
    update_interval: 30s
    lambda: "return id(modbus_counter_raw);"
    web_server:
      sorting_group_id: sys_health

button:
  - platform: template
    name: modbus_soft_reset
    icon: mdi:restart
    web_server:
      sorting_group_id: sys_health
    on_press:
      then:
        - lambda: 'id(modbus_bus).setup();'
