---
name: esphome-lint.yml

on:
  push:
    branches:
      - main
    paths:
      - '*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '*.yaml'

jobs:
  validate-config:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v7

      - name: Install ESPHome Validator Engine
        run: |
          pip install esphome

      - name: Run Validation Checks on ESP32-C6 YAML
        run: |
          esphome config esp32-c6-elt-12k.yaml
      - name: Run Validation Checks on ESP32-S3 YAML
        run: |
          esphome config esp32-s3-elt-12k.yaml
